- name: "Setting Drupal in ubuntu"
  hosts: ubuntu
  become: yes
  vars_files:
    - ../vars/installs.yaml
    - ../vars/services.yaml
    - ../vars/mariaDB.yaml
    - ../vars/certbot.yaml

  pre_tasks:

    - name: "Updating cache"
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:

    - name: "file: Creating drupal directory"
      file:
        path: /drupal/
        state: directory

    - name: "get_url: Downloading drupal"
      get_url:
        url: https://www.drupal.org/download-latest/tar.gz
        dest: /drupal/drupal.tar.gz

    - name: "file: creating drupal directory in /var/www/html/"
      file:
        path: /var/www/html/drupal/
        state: directory

    - name: "unarchive: unarchiving tar files"
      unarchive:
        src: /drupal/drupal.tar.gz
        dest: /var/www/html/drupal/
        remote_src: yes

    - name: "file: changing access to /var/www/html/drupal/"
      file:
        path: /var/www/html/drupal/
        owner: "www-data"
        group: "www-data"
        state: directory
        recurse: yes
        mode: '755'

    - name: "file: creating drupal.conf file"
      file:
        path: /etc/apache2/sites-available/drupal.conf
        state: touch

    - name: "copy: copying content to config file"
      copy:
        src: ../required/drupal.conf
        dest: /etc/apache2/sites-available/drupal.conf

    - name: "Shell: Enable Drupal site"
      command: a2ensite drupal.conf
      notify: restart apache2

    - name: "Sehll: Enable Apache rewrite module"
      command: a2enmod rewrite
      notify: restart apache2

    - name: "Shell: Test Apache configuration"
      command: apachectl -t
      notify: restart apache2

  handlers:
    - import_tasks: ../handlers/dp_handlers.yaml
